### ISSUE TITLE
Firefox - Torque Issues?

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/torque#161] opened 2015-03-27 17:55 UTC
Torque issues in Firefox? [User](https://twitter.com/MapBaker/status/581511106650185728) is having trouble loading Water Day blog post in Firefox.

**Comment by rochoa** [comment] 2015-03-30 17:50
It seems to be the `Major Dams and US River Basins` heatmap map: http://team.cartodb.com/u/chandra/viz/f4efdd96-cdc0-11e4-bdef-0e8dde98a187/public_map

![screen shot 2015-03-30 at 19 48 55](https://cloud.githubusercontent.com/assets/45346/6902742/f874268a-d715-11e4-8ae3-90bf39fd3189.png)

**Comment by fdansv** [comment] 2015-04-21 17:38
Duplicate of #104 and https://github.com/CartoDB/cartodb/issues/2121 . Cumulative heatmaps need optimization, as right now getting pixel information for the canvas is too expensive for them to be smooth.

**Closed by fdansv** 2015-04-21 17:38 UTC
